compute_board/firwmare: fix teensy3 compilation error
Problem: pins_teensy.c cannot find getIsrTable() inline function.

  arm-none-eabi-gcc -Os -Wl,--gc-sections,--defsym=__rtc_localtime=0 --specs=nano.specs -mcpu=cortex-m4 -mthumb -Tteensy3/mk20dx256.ld -Wl,--no-wchar-size-warning -o main.elf teensy3/mk20dx128.o teensy3/pins_teensy.o teensy3/serial1.o teensy3/serial2.o teensy3/serial3.o teensy3/nonstd.o teensy3/analog.o teensy3/usb_dev.o teensy3/usb_mem.o teensy3/usb_serial.o teensy3/usb_desc.o main.o canmgr.o address.o canmgr_proto.o teensy3/yield.o teensy3/HardwareSerial1.o teensy3/HardwareSerial2.o teensy3/HardwareSerial3.o teensy3/usb_inst.o FlexCAN/FlexCAN.o Entropy/Entropy.o can.o identify.o activity.o target_reset.o target_power.o target_console.o heartbeat.o -lm
  /opt/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: teensy3/pins_teensy.o: in function `attachInterrupt':
  teensy3/pins_teensy.c:219: undefined reference to `getIsrTable'
  /opt/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: teensy3/pins_teensy.o: in function `detachInterrupt':
  teensy3/pins_teensy.c:250: undefined reference to `getIsrTable'
  collect2: error: ld returned 1 exit status
  Makefile:92: recipe for target 'main.elf' failed
  make: *** [main.elf] Error 1

Solution: define getIsrTable as 'static inline' instead of 'inline'.